name: testDownload

on:
  workflow_dispatch:

jobs:
  build:
    name: downloadfromOutside
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        repository: tyjeon24/downloadMe
    - run: ls -al
